const readingLanguages = <String, String>{
  'en': 'English',
  'fr': 'French',
  'es': 'Spanish',
  'de': 'German',
  'pt': 'Portuguese',
  'it': 'Italian',
  'ar': 'Arabic',
  'hi': 'Hindi',
  'zh': 'Chinese',
  'ja': 'Japanese',
  'ko': 'Korean',
  'nl': 'Dutch',
  'pl': 'Polish',
  'tr': 'Turkish',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'ha': 'Hausa',
};
